DIRS = 

##################################
# Output File in this library, Only use one.
##################################

MODE=static

##################################
# Include library
##################################
# include share library
INC_SHARELIBS = libconfig.so libsio.so libsystem.so 
# include static library
INC_STATICLIBS = 



include $(TOP)/make.dep

