DIRS =

##################################
# Output Mode.
##################################
MODE=static

##################################
# Include library
##################################
# include share library
INC_SHARELIBS = libconfig.so libsio.so libsystem.so
# include static library
INC_STATICLIBS =



include $(TOP)/make.dep

