DIRS = 

##################################
# Output Mode.
##################################
MODE=static

##################################
# Include library
##################################
# include share library
INC_SHARELIBS =
# include static library
INC_STATICLIBS = 



include $(TOP)/make.dep

